package lk.ijse.salongeetha.dao;

public enum DAOImplTypes {
    APPOINTMENT, BILL, BOOKING, BOOING_RENTALS, CUSTOMER, EMPLOYEE, EMPLOYEE_SERVICE, LOGIN, PAYMENT, PRODUCT,
    PRODUCT_SERVICE, QUERY,RENTALS,SERVICE_APPOINTMENT,SERVICE,SUPPLIER,USER
}
