package lk.ijse.salongeetha.bo;

public enum BOImplTypes {
    ADD_ADMIN,ADD_CUSTOMER,APPOINTMENT, BILL, BOOKING,CREATE_PASSWORD, CUSTOMER, EMPLOYEE, EMPLOYEE_SERVICE,
    FORGOT_PASSWORD,HOME, LOGIN,MAIN, PAYMENT, PRODUCT, PRODUCT_SERVICE, RECEPTIONIST_HOME,RENTALS,
    REPORTS,SERVICE,SUPPLIER,UPDATE_CUSTOMER
}
